name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Create diff
        run: git --no-pager diff HEAD^ HEAD > last_commit.patch
        
      - uses: actions/setup-node@v2
      
      - name: Upload to Carbon
        run: npx carbon-now-cli

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
