name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Create diff
        run: git --no-pager diff HEAD^ HEAD > last_commit.patch
        
      - name: Download Germanium (code2img)
        run: |
          wget -q https://github.com/matsuyoshi30/germanium/releases/download/v1.2.2/germanium_1.2.2_linux_x86_64.tar.gz
          tar xvf germanium_1.2.2_linux_x86_64.tar.gz
          
      - name: Generate code diff
        run: ./germanium -o output.png --no-window-access-bar last_commit.patch
        
      - uses: actions/upload-artifact@v2
        with:
          name: diff.png
          path: output.png

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
